name: "Hello"
description: "Greeting"
inputs:
  user-name:
    description: "User Name"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo Hello ${{ inputs.user-name }}
