name: CI

on:
  push:
    branches:
      - develop

jobs:
  mariadb_test:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"

      - name: Check Node & npm Version
        run: |
          node --version
          npm --version

      - name: Setup MariaDB
        shell: bash
        env:
          MYSQL_DATABASE: testdb
        run: |
          docker-compose -f ${{ github.workspace }}/docker/docker-compose.yml up -d

      - name: Run Test
        run: |
          npm ci
          npm run test
