name: TMP

on:
  workflow_dispatch:

jobs:
  temporary:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Hello
        uses: ./.github/actions/hello
